# SPDX-FileCopyrightText: 2024 Alex Turbov <i.zaufi@gmail.com>
# SPDX-License-Identifier: CC0-1.0

# See docs here:
# https://github.com/DavidAnson/markdownlint/blob/main/README.md#rules--aliases

default: true

MD012:
  # Consecutive blank lines
  maximum: 2

MD013:
  line_length: 120
