# SPDX-FileCopyrightText: 2026 Alex Turbov <i.zaufi@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later

cmake_policy(SET CMP0140 NEW)

if(NOT DEFINED INPUT_FILE)
    message(FATAL_ERROR "INPUT_FILE is not set")
endif()

if(NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "OUTPUT_FILE is not set")
endif()

if(NOT DEFINED TEMPLATE_FILE)
    message(FATAL_ERROR "TEMPLATE_FILE is not set")
endif()

foreach(_var INPUT_FILE OUTPUT_FILE TEMPLATE_FILE)
    string(REGEX REPLACE "^\"(.*)\"$" "\\1" ${_var} "${${_var}}")
endforeach()

function(_json_get_or_empty OUT_VAR JSON_TEXT)
    string(JSON _value ERROR_VARIABLE _error GET "${JSON_TEXT}" ${ARGN})
    if(_error)
        set(_value "")
    endif()
    set(${OUT_VAR} "${_value}")
    return(PROPAGATE ${OUT_VAR})
endfunction()

if(NOT EXISTS "${INPUT_FILE}")
    message(FATAL_ERROR "Input file does not exist: ${INPUT_FILE}")
endif()

file(READ "${INPUT_FILE}" _charmaps_json)
string(JSON _charmaps_count LENGTH "${_charmaps_json}")
file(READ "${TEMPLATE_FILE}" _charmap_template)

cmake_path(GET OUTPUT_FILE PARENT_PATH _output_dir)
file(MAKE_DIRECTORY "${_output_dir}")

file(WRITE "${OUTPUT_FILE}" [=[
#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Alex Turbov <i.zaufi@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later

# DO NOT EDIT! This file is generated by CMake from `charmaps.yaml`.

]=])

set(_generated_functions "")

if(_charmaps_count GREATER 0)
    math(EXPR _charmaps_last "${_charmaps_count} - 1")
    foreach(_charmap_index RANGE 0 ${_charmaps_last})
        string(JSON _charmap_name MEMBER "${_charmaps_json}" ${_charmap_index})
        _json_get_or_empty(_digits "${_charmaps_json}" ${_charmap_name} digits)
        _json_get_or_empty(_alpha_lower "${_charmaps_json}" ${_charmap_name} alpha lower)
        _json_get_or_empty(_alpha_upper "${_charmaps_json}" ${_charmap_name} alpha upper)
        message(STATUS "Rendering charmap: ${_charmap_name}")
        unset(_input_alphabet)
        unset(_output_alphabet)
        if(_digits)
            string(APPEND _input_alphabet "0123456789")
            string(APPEND _output_alphabet "${_digits}")
        endif()
        if(_alpha_lower)
            string(APPEND _input_alphabet "abcdefghijklmnopqrstuvwxyz")
            string(APPEND _output_alphabet "${_alpha_lower}")
        endif()
        if(_alpha_upper)
            if(NOT _alpha_lower)
                string(APPEND _input_alphabet "abcdefghijklmnopqrstuvwxyz")
                string(APPEND _output_alphabet "${_alpha_upper}")
            endif()
            string(APPEND _input_alphabet "ABCDEFGHIJKLMNOPQRSTUVWXYZ")
            string(APPEND _output_alphabet "${_alpha_upper}")
        endif()
        string(CONFIGURE "${_charmap_template}" _rendered_function @ONLY)
        string(APPEND _generated_functions "${_rendered_function}\n")
    endforeach()
endif()

file(APPEND "${OUTPUT_FILE}" "${_generated_functions}")

message(STATUS "Generated placeholder bash file: ${OUTPUT_FILE}")
