#
# SPDX-FileCopyrightText: 2024 Alex Turbov <i.zaufi@gmail.com>
# SPDX-License-Identifier: CC0-1.0
#

version = 1
SPDX-PackageName = "smart-prompt"
SPDX-PackageSupplier = "Alex Turbov <i.zaufi@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/zaufi/smart-prompt"

[[annotations]]
path = ".reuse-hdrmap.json"
precedence = "override"
SPDX-FileCopyrightText = "Alex Turbov <i.zaufi@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".github/pull_request_template.md"
precedence = "override"
SPDX-FileCopyrightText = "Alex Turbov <i.zaufi@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"
